package com.app.sancus.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.app.sancus.moddel.User;
import com.app.sancus.moddel.UserRequest;
import com.app.sancus.moddel.UserResponse;
import com.app.sancus.service.IUserService;
import com.app.sancus.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserController {

	@Autowired
	private IUserService service;

	@Autowired
	private JwtUtil util;

	@Autowired
	private AuthenticationManager authenticationManager;
	// save user 
	@PostMapping("/save")
	public ResponseEntity<String> saveUser(@RequestBody User user){

		Integer	id=service.save(user);
		String body="User '"+id+"' saved";	
		//return new ResponseEntity<String>(body,HttpStatus.OK);
		//above line 27 is equal to line 29
		return ResponseEntity.ok(body);
	}

	//2.validate user and generate token(login)
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request){

		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						request.getUsername(), request.getPassword()));
		String token=util.generateToken(request.getUsername());
		return ResponseEntity.ok(
				new UserResponse(token,"Success! Generated By PARALA NAVEEN")
				);
	}
	
	//3.after login only
	@PostMapping("/welcome")
	public ResponseEntity<String> accessData(Principal p){
		return ResponseEntity.ok("Hello User!"+p.getName());	}
}
